#include "gfx/core/keyboard.hpp"

#include <SFML/Window/Keyboard.hpp>

namespace gfx {
namespace core {

namespace detail {

#define CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( key )                                     \
    case Keyboard::key:                                                                            \
        return sf::Keyboard::key;

sf::Keyboard::Key
toSFML( Keyboard::Key key )
{
    switch ( key )
    {
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Unknown );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( A );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( B );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( C );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( D );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( E );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( F );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( G );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( H );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( I );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( J );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( K );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( L );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( M );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( N );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( O );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( P );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Q );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( R );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( S );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( T );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( U );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( V );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( W );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( X );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Y );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Z );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Num0 );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Num1 );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Num2 );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Num3 );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Num4 );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Num5 );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Num6 );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Num7 );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Num8 );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Num9 );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Escape );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( LControl );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( LShift );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( LAlt );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( LSystem );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( RControl );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( RShift );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( RAlt );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( RSystem );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Menu );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( LBracket );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( RBracket );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Semicolon );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Comma );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Period );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Apostrophe );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Slash );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Backslash );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Grave );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Equal );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Hyphen );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Space );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Enter );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Backspace );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Tab );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( PageUp );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( PageDown );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( End );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Home );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Insert );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Delete );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Add );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Subtract );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Multiply );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Divide );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Left );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Right );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Up );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Down );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Numpad0 );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Numpad1 );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Numpad2 );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Numpad3 );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Numpad4 );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Numpad5 );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Numpad6 );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Numpad7 );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Numpad8 );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Numpad9 );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( F1 );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( F2 );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( F3 );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( F4 );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( F5 );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( F6 );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( F7 );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( F8 );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( F9 );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( F10 );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( F11 );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( F12 );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( F13 );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( F14 );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( F15 );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( Pause );
        CASE_GFX_CORE_KEYBOARD_KEY_TO_SFML_KEYBOARD_KEY( KeyCount );
        default:
            return sf::Keyboard::Unknown;
    }
}

#define CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( key )                                     \
    case sf::Keyboard::key:                                                                        \
        return Keyboard::key;

Keyboard::Key
fromSFML( sf::Keyboard::Key key )
{
    switch ( key )
    {
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Unknown );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( A );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( B );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( C );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( D );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( E );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( F );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( G );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( H );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( I );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( J );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( K );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( L );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( M );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( N );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( O );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( P );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Q );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( R );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( S );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( T );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( U );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( V );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( W );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( X );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Y );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Z );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Num0 );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Num1 );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Num2 );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Num3 );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Num4 );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Num5 );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Num6 );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Num7 );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Num8 );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Num9 );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Escape );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( LControl );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( LShift );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( LAlt );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( LSystem );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( RControl );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( RShift );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( RAlt );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( RSystem );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Menu );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( LBracket );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( RBracket );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Semicolon );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Comma );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Period );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Apostrophe );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Slash );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Backslash );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Grave );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Equal );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Hyphen );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Space );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Enter );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Backspace );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Tab );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( PageUp );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( PageDown );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( End );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Home );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Insert );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Delete );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Add );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Subtract );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Multiply );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Divide );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Left );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Right );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Up );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Down );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Numpad0 );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Numpad1 );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Numpad2 );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Numpad3 );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Numpad4 );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Numpad5 );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Numpad6 );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Numpad7 );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Numpad8 );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Numpad9 );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( F1 );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( F2 );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( F3 );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( F4 );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( F5 );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( F6 );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( F7 );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( F8 );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( F9 );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( F10 );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( F11 );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( F12 );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( F13 );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( F14 );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( F15 );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( Pause );
        CASE_SFML_KEYBOARD_KEY_TO_GFX_CORE_KEYBOARD_KEY( KeyCount );
        default:
            return Keyboard::Unknown;
    }
}

} // namespace detail

bool
Keyboard::isKeyPressed( Keyboard::Key key )
{
    return sf::Keyboard::isKeyPressed( detail::toSFML( key ) );
}

} // namespace core
} // namespace gfx
